lista = [] # list()
print(lista)
lista.append(2)
print(lista)
lista.append('Hola')
print(lista)
lista.append([2,3,4])
print(lista)
lista.append(2.2)
print(lista)
lista.append(True)
print(lista)
lista.append(2)
print(lista)