lista = []
print(list(lista))
lista.append(1)
print(list(lista))
lista.append(2)
print(list(lista))
lista.append(3)
print(list(lista))
lista.append(4)
print(list(lista))
lista.append(5)
print(list(lista))
lista.append(6)
print(list(lista))
